### PR TITLE
Updates the podspec to resolve build issues with M1 Macs

### PR DESCRIPTION
**Pull request by subdigital**
I ran into an issue getting our project to build on M1 Macs. Upstream had the same issue so I merged those pod spec changes into our fork.

### CODE REVIEW

**Comment by subdigital** [comment]
@mlink I don't think we need to wait for the Carthage build to pass since we don't use it. It failed twice for reasons I don't understand.

**Comment by subdigital** [comment]
@mlink any reason we can't merge this?

**Comment by subdigital** [comment]
(for context, this is a pre-requisite for [this pr](https://github.com/spin-org/spin-mobile/pull/2976) )

**Review by mlink — APPROVED** [review]
LGTM, sorry I must have missed the original notifications for this review

**Pull request merged**
